/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package circuitsimulator;

/**
 *
 * @author tklw06
 */
public class CircuitSimulatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CircuitSimulator2
     */
    public CircuitSimulatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        mainWindow = new javax.swing.JPanel();
        circuitImageMultiLoop = new javax.swing.JLabel();
        circuitName = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        inputWindow = new javax.swing.JPanel();
        seriesInputInfo = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        CircuitSelectorPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        outputWindow = new javax.swing.JPanel();
        battVoltTitleA = new javax.swing.JLabel();
        battVoltTitleB = new javax.swing.JLabel();
        battVoltTitleTotal = new javax.swing.JLabel();
        battVoltTitleC = new javax.swing.JLabel();
        battVoltTitleD = new javax.swing.JLabel();
        outputVoltA = new javax.swing.JTextField();
        outputVoltB = new javax.swing.JTextField();
        outputVoltC = new javax.swing.JTextField();
        outputVoltD = new javax.swing.JTextField();
        outputVoltTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circuitImageMultiLoop.setBackground(java.awt.Color.white);
        circuitImageMultiLoop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/multiloop.png"))); // NOI18N
        mainWindow.add(circuitImageMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 412, 286));

        circuitName.setText("Circuit: [.......]");
        mainWindow.add(circuitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, -1, -1));

        status.setText("Status: [......]");
        mainWindow.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 28, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/parallelinseries.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        mainWindow.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 400, 290));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/parallel.png"))); // NOI18N
        mainWindow.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 400, 290));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/series.png"))); // NOI18N
        mainWindow.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 290));

        inputWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Information"));
        inputWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        javax.swing.GroupLayout seriesInputInfoLayout = new javax.swing.GroupLayout(seriesInputInfo);
        seriesInputInfo.setLayout(seriesInputInfoLayout);
        seriesInputInfoLayout.setHorizontalGroup(
            seriesInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seriesInputInfoLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(seriesInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        seriesInputInfoLayout.setVerticalGroup(
            seriesInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriesInputInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        inputWindow.add(seriesInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 230));

        mainWindow.add(inputWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 270, 280));

        CircuitSelectorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Circuit Selection"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout CircuitSelectorPanelLayout = new javax.swing.GroupLayout(CircuitSelectorPanel);
        CircuitSelectorPanel.setLayout(CircuitSelectorPanelLayout);
        CircuitSelectorPanelLayout.setHorizontalGroup(
            CircuitSelectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CircuitSelectorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        CircuitSelectorPanelLayout.setVerticalGroup(
            CircuitSelectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CircuitSelectorPanelLayout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainWindow.add(CircuitSelectorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 270, 50));

        outputWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Information"));
        outputWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        battVoltTitleA.setText("Voltage (A):");
        outputWindow.add(battVoltTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        battVoltTitleB.setText("Voltage (B):");
        outputWindow.add(battVoltTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        battVoltTitleTotal.setText("Total voltage: ");
        outputWindow.add(battVoltTitleTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        battVoltTitleC.setText("Voltage (C):");
        outputWindow.add(battVoltTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        battVoltTitleD.setText("Voltage (D): ");
        outputWindow.add(battVoltTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        outputVoltA.setText("jTextField6");
        outputWindow.add(outputVoltA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        outputVoltB.setText("jTextField7");
        outputWindow.add(outputVoltB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        outputVoltC.setText("jTextField8");
        outputWindow.add(outputVoltC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        outputVoltD.setText("jTextField9");
        outputWindow.add(outputVoltD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        outputVoltTotal.setText("jTextField6");
        outputWindow.add(outputVoltTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel1.setText("Resistance (A): ");
        outputWindow.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 20));

        jLabel9.setText("Resistance (B):");
        outputWindow.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addComponent(outputWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outputWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircuitSimulatorGUI().setVisible(true);
            }
        });
    }

    /*
        //create array
        int[][] numbers = new int[10][12]; //10 rows. 4 will be default 
                                           //presets, hopefully the rest can be made?
        //initialize array: rows then columns
        for(int i = 0; i < numbers.length; i++){
            for (int n = 0; n < numbers[i].length; n++){
                numbers[i][n] = i*n;
            }
        } 
    */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CircuitSelectorPanel;
    private javax.swing.JLabel battVoltTitleA;
    private javax.swing.JLabel battVoltTitleB;
    private javax.swing.JLabel battVoltTitleC;
    private javax.swing.JLabel battVoltTitleD;
    private javax.swing.JLabel battVoltTitleTotal;
    private javax.swing.JLabel circuitImageMultiLoop;
    private javax.swing.JLabel circuitName;
    private javax.swing.JPanel inputWindow;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel mainWindow;
    private javax.swing.JTextField outputVoltA;
    private javax.swing.JTextField outputVoltB;
    private javax.swing.JTextField outputVoltC;
    private javax.swing.JTextField outputVoltD;
    private javax.swing.JTextField outputVoltTotal;
    private javax.swing.JPanel outputWindow;
    private javax.swing.JPanel seriesInputInfo;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
