package circuitsimulator;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author tklw06
 */
public class UI extends javax.swing.JFrame {

    // for the action listener dropdown menu
    public final static int SERIES = 0;
    public final static int PARALLEL = 1;
    public final static int PARALLEL_IN_SERIES = 2;
    public final static int MULTI_LOOP = 3;
    
    private int circuitType = 0;
    
    private CircuitBucket cb = new CircuitBucket();
    
    /**
     * Creates new form CircuitSimulator2
     */
    public UI() {
        initComponents();
        clearImage();
        Persistor pers = new Persistor();
        try {
            pers.initiate();
            pers.read(cb);
        }
        catch (IOException e){
            System.out.println("\n*** " + e.getMessage() + "\n");
        }
        catch (Exception e){
            System.out.println("\n*** " + e.getMessage() + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindow = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        seriesImage = new javax.swing.JLabel();
        parallelInSeriesImage = new javax.swing.JLabel();
        parallelImage = new javax.swing.JLabel();
        multiLoopImage = new javax.swing.JLabel();
        inputWindow = new javax.swing.JPanel();
        numberOfBatteriesLabel = new javax.swing.JLabel();
        voltagePerBatteryLabel = new javax.swing.JLabel();
        numberOfBatteriesInput = new javax.swing.JTextField();
        voltagePerBatteryInput = new javax.swing.JTextField();
        multiLoopInputInfo = new javax.swing.JPanel();
        numberOfResistorsTitleA2 = new javax.swing.JLabel();
        resistancePerResistorTitleA3 = new javax.swing.JLabel();
        rPerRInputAMultiLoop = new javax.swing.JTextField();
        noOfRInputAMultiLoop = new javax.swing.JTextField();
        numberOfResistorsTitleB1 = new javax.swing.JLabel();
        resistancePerResistorTitleB1 = new javax.swing.JLabel();
        noOfRInputBMultiLoop = new javax.swing.JTextField();
        rPerRInputBMultiLoop = new javax.swing.JTextField();
        numberOfResistorsTitleC1 = new javax.swing.JLabel();
        resistancePerResistorTitleC1 = new javax.swing.JLabel();
        noOfRInputCMultiLoop = new javax.swing.JTextField();
        rPerRInputCMultiLoop = new javax.swing.JTextField();
        numberOfResistorsTitleD = new javax.swing.JLabel();
        resistancePerResistorTitleD = new javax.swing.JLabel();
        noOfRInputDMultiLoop = new javax.swing.JTextField();
        rPerRInputDMultiLoop = new javax.swing.JTextField();
        seriesInputInfo = new javax.swing.JPanel();
        numberOfResistorsAtATitle = new javax.swing.JLabel();
        resistancePerResistorATitle = new javax.swing.JLabel();
        rPerRInputASeries = new javax.swing.JTextField();
        noOfRInputASeries = new javax.swing.JTextField();
        parallelInputInfo = new javax.swing.JPanel();
        numberOfResistorsTitleA = new javax.swing.JLabel();
        resistancePerResistorTitleA = new javax.swing.JLabel();
        rPerRInputAParallel = new javax.swing.JTextField();
        noOfRInputAParallel = new javax.swing.JTextField();
        numberOfResistorsTitleB = new javax.swing.JLabel();
        resistancePerResistorTitleB = new javax.swing.JLabel();
        noOfRInputBParallel = new javax.swing.JTextField();
        rPerRInputBParallel = new javax.swing.JTextField();
        parallelInSeriesInputInfo = new javax.swing.JPanel();
        numberOfResistorsTitleA1 = new javax.swing.JLabel();
        resistancePerResistorTitleA1 = new javax.swing.JLabel();
        rPerRInputAParallelInSeries = new javax.swing.JTextField();
        noOfRInputAParallelInSeries = new javax.swing.JTextField();
        numberOfResistorsTitleC = new javax.swing.JLabel();
        resistancePerResistorTitleC = new javax.swing.JLabel();
        noOfRInputCParallelInSeries = new javax.swing.JTextField();
        rPerRInputCParallelInSeries = new javax.swing.JTextField();
        CircuitSelectorPanel = new javax.swing.JPanel();
        circuitMenu = new javax.swing.JComboBox();
        runButton = new javax.swing.JButton();
        runningOKLabel = new javax.swing.JLabel();
        idleLabel = new javax.swing.JLabel();
        outputWindow = new javax.swing.JPanel();
        battVoltTitleA = new javax.swing.JLabel();
        battVoltTitleB = new javax.swing.JLabel();
        battVoltTitleTotal = new javax.swing.JLabel();
        battVoltTitleC = new javax.swing.JLabel();
        battVoltTitleD = new javax.swing.JLabel();
        outputVoltA = new javax.swing.JTextField();
        outputVoltB = new javax.swing.JTextField();
        outputVoltC = new javax.swing.JTextField();
        outputVoltD = new javax.swing.JTextField();
        outputVoltTotal = new javax.swing.JTextField();
        resistanceTitleA = new javax.swing.JLabel();
        resistanceTitleB = new javax.swing.JLabel();
        resistanceTitleC = new javax.swing.JLabel();
        resistanceTitleD = new javax.swing.JLabel();
        resistanceTitleTotal = new javax.swing.JLabel();
        outputRA = new javax.swing.JTextField();
        outputRB = new javax.swing.JTextField();
        outputRC = new javax.swing.JTextField();
        outputRD = new javax.swing.JTextField();
        outputRTotal = new javax.swing.JTextField();
        powerOutputTitle = new javax.swing.JLabel();
        voltageOutputTitle = new javax.swing.JLabel();
        currentTitleA = new javax.swing.JLabel();
        currentTitleB = new javax.swing.JLabel();
        currentTitleC = new javax.swing.JLabel();
        currentTitleD = new javax.swing.JLabel();
        currentTitleTotal = new javax.swing.JLabel();
        outputIA = new javax.swing.JTextField();
        outputIB = new javax.swing.JTextField();
        outputIC = new javax.swing.JTextField();
        outputID = new javax.swing.JTextField();
        outputITotal = new javax.swing.JTextField();
        outputPA = new javax.swing.JTextField();
        outputPB = new javax.swing.JTextField();
        outputPC = new javax.swing.JTextField();
        outputPD = new javax.swing.JTextField();
        outputPTotal = new javax.swing.JTextField();
        powerTitleA = new javax.swing.JLabel();
        powerTitleB = new javax.swing.JLabel();
        powerTitleC = new javax.swing.JLabel();
        powerTitleD = new javax.swing.JLabel();
        powerTitleTotal = new javax.swing.JLabel();
        resistanceOutputTitle = new javax.swing.JLabel();
        currentOutputTitle = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        aboutThis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Circuit Simulator 2011");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusLabel.setText("Status: ");
        mainWindow.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        seriesImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/series.png"))); // NOI18N
        mainWindow.add(seriesImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 290));

        parallelInSeriesImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/parallelinseries.png"))); // NOI18N
        parallelInSeriesImage.setText("jLabel12");
        mainWindow.add(parallelInSeriesImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 290));

        parallelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/parallel.png"))); // NOI18N
        mainWindow.add(parallelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 290));

        multiLoopImage.setBackground(java.awt.Color.white);
        multiLoopImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/multiloop.png"))); // NOI18N
        mainWindow.add(multiLoopImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 412, 286));

        inputWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Information"));
        inputWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfBatteriesLabel.setText("Number of batteries:");
        inputWindow.add(numberOfBatteriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        voltagePerBatteryLabel.setText("Emf per battery: ");
        inputWindow.add(voltagePerBatteryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        numberOfBatteriesInput.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        numberOfBatteriesInput.setToolTipText("Please fill in this field.");
        inputWindow.add(numberOfBatteriesInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 50, 20));

        voltagePerBatteryInput.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        voltagePerBatteryInput.setToolTipText("Please fill in this field.");
        inputWindow.add(voltagePerBatteryInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 50, 20));

        multiLoopInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfResistorsTitleA2.setText("Number of resistors (A):");
        multiLoopInputInfo.add(numberOfResistorsTitleA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        resistancePerResistorTitleA3.setText("Resistance per resistor (A): ");
        multiLoopInputInfo.add(resistancePerResistorTitleA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 180, -1));

        rPerRInputAMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputAMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(rPerRInputAMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, 20));

        noOfRInputAMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputAMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(noOfRInputAMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, 20));

        numberOfResistorsTitleB1.setText("Number of resistors (B):");
        multiLoopInputInfo.add(numberOfResistorsTitleB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 172, -1));

        resistancePerResistorTitleB1.setText("Resistance per resistor (B): ");
        multiLoopInputInfo.add(resistancePerResistorTitleB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        noOfRInputBMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputBMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(noOfRInputBMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 50, 20));

        rPerRInputBMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputBMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(rPerRInputBMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 50, 20));

        numberOfResistorsTitleC1.setText("Number of resistors (C):");
        multiLoopInputInfo.add(numberOfResistorsTitleC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 172, -1));

        resistancePerResistorTitleC1.setText("Resistance per resistor (C): ");
        multiLoopInputInfo.add(resistancePerResistorTitleC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, -1));

        noOfRInputCMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputCMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(noOfRInputCMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 50, 20));

        rPerRInputCMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputCMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(rPerRInputCMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 50, 20));

        numberOfResistorsTitleD.setText("Number of resistors (D):");
        multiLoopInputInfo.add(numberOfResistorsTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 172, -1));

        resistancePerResistorTitleD.setText("Resistance per resistor (D): ");
        multiLoopInputInfo.add(resistancePerResistorTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, -1));

        noOfRInputDMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputDMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(noOfRInputDMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 20));

        rPerRInputDMultiLoop.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputDMultiLoop.setToolTipText("Please fill in this field.");
        multiLoopInputInfo.add(rPerRInputDMultiLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 50, 20));

        inputWindow.add(multiLoopInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, 220));

        seriesInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfResistorsAtATitle.setText("Number of resistors: ");
        seriesInputInfo.add(numberOfResistorsAtATitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        resistancePerResistorATitle.setText("Resistance per resistor: ");
        seriesInputInfo.add(resistancePerResistorATitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 163, -1));

        rPerRInputASeries.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputASeries.setText("jTextField7");
        seriesInputInfo.add(rPerRInputASeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, 20));

        noOfRInputASeries.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputASeries.setText("jTextField7");
        seriesInputInfo.add(noOfRInputASeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, 20));

        inputWindow.add(seriesInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, 220));

        parallelInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfResistorsTitleA.setText("Number of resistors (A):");
        parallelInputInfo.add(numberOfResistorsTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        resistancePerResistorTitleA.setText("Resistance per resistor (A): ");
        parallelInputInfo.add(resistancePerResistorTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 180, -1));

        rPerRInputAParallel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputAParallel.setText("jTextField7");
        parallelInputInfo.add(rPerRInputAParallel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, 20));

        noOfRInputAParallel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputAParallel.setText("jTextField7");
        parallelInputInfo.add(noOfRInputAParallel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, 20));

        numberOfResistorsTitleB.setText("Number of resistors (B):");
        parallelInputInfo.add(numberOfResistorsTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 172, -1));

        resistancePerResistorTitleB.setText("Resistance per resistor (B): ");
        parallelInputInfo.add(resistancePerResistorTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        noOfRInputBParallel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputBParallel.setText("jTextField7");
        parallelInputInfo.add(noOfRInputBParallel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 50, 20));

        rPerRInputBParallel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputBParallel.setText("jTextField7");
        parallelInputInfo.add(rPerRInputBParallel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 50, 20));

        inputWindow.add(parallelInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, 220));

        parallelInSeriesInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfResistorsTitleA1.setText("Number of resistors (A):");
        parallelInSeriesInputInfo.add(numberOfResistorsTitleA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        resistancePerResistorTitleA1.setText("Resistance per resistor (A): ");
        parallelInSeriesInputInfo.add(resistancePerResistorTitleA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 180, -1));

        rPerRInputAParallelInSeries.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputAParallelInSeries.setText("jTextField7");
        parallelInSeriesInputInfo.add(rPerRInputAParallelInSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, 20));

        noOfRInputAParallelInSeries.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputAParallelInSeries.setText("jTextField7");
        parallelInSeriesInputInfo.add(noOfRInputAParallelInSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, 20));

        numberOfResistorsTitleC.setText("Number of resistors (C):");
        parallelInSeriesInputInfo.add(numberOfResistorsTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 172, -1));

        resistancePerResistorTitleC.setText("Resistance per resistor (C): ");
        parallelInSeriesInputInfo.add(resistancePerResistorTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        noOfRInputCParallelInSeries.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        noOfRInputCParallelInSeries.setText("jTextField7");
        parallelInSeriesInputInfo.add(noOfRInputCParallelInSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 50, 20));

        rPerRInputCParallelInSeries.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        rPerRInputCParallelInSeries.setText("jTextField7");
        parallelInSeriesInputInfo.add(rPerRInputCParallelInSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 50, 20));

        inputWindow.add(parallelInSeriesInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, 220));

        mainWindow.add(inputWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 380, 290));

        CircuitSelectorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Circuit Selection"));
        CircuitSelectorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circuitMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Series", "Parallel", "Parallel in series", "Multi loop" }));
        circuitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuitMenuActionPerformed(evt);
            }
        });
        CircuitSelectorPanel.add(circuitMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 360, -1));

        mainWindow.add(CircuitSelectorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 380, 50));

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });
        mainWindow.add(runButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        runningOKLabel.setText("Running OK!");
        mainWindow.add(runningOKLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        idleLabel.setText("Select a circuit and hit Run to get started!");
        mainWindow.add(idleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        outputWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Information"));
        outputWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        battVoltTitleA.setText("Voltage (A):");
        outputWindow.add(battVoltTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        battVoltTitleB.setText("Voltage (B):");
        outputWindow.add(battVoltTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        battVoltTitleTotal.setText("Total voltage: ");
        outputWindow.add(battVoltTitleTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        battVoltTitleC.setText("Voltage (C):");
        outputWindow.add(battVoltTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        battVoltTitleD.setText("Voltage (D): ");
        outputWindow.add(battVoltTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        outputVoltA.setEditable(false);
        outputVoltA.setBackground(new java.awt.Color(204, 204, 204));
        outputVoltA.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputVoltA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 70, 20));

        outputVoltB.setEditable(false);
        outputVoltB.setBackground(new java.awt.Color(204, 204, 204));
        outputVoltB.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputVoltB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, 20));

        outputVoltC.setEditable(false);
        outputVoltC.setBackground(new java.awt.Color(204, 204, 204));
        outputVoltC.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputVoltC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 70, 20));

        outputVoltD.setEditable(false);
        outputVoltD.setBackground(new java.awt.Color(204, 204, 204));
        outputVoltD.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputVoltD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, 20));

        outputVoltTotal.setEditable(false);
        outputVoltTotal.setBackground(new java.awt.Color(204, 204, 204));
        outputVoltTotal.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputVoltTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 20));

        resistanceTitleA.setText("Resistance (A): ");
        outputWindow.add(resistanceTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 20));

        resistanceTitleB.setText("Resistance (B):");
        outputWindow.add(resistanceTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        resistanceTitleC.setText("Resistance (C): ");
        outputWindow.add(resistanceTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        resistanceTitleD.setText("Resistance (D):");
        outputWindow.add(resistanceTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        resistanceTitleTotal.setText("Total resistance: ");
        outputWindow.add(resistanceTitleTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        outputRA.setEditable(false);
        outputRA.setBackground(new java.awt.Color(204, 204, 204));
        outputRA.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, 20));

        outputRB.setEditable(false);
        outputRB.setBackground(new java.awt.Color(204, 204, 204));
        outputRB.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 70, 20));

        outputRC.setEditable(false);
        outputRC.setBackground(new java.awt.Color(204, 204, 204));
        outputRC.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 70, 20));

        outputRD.setEditable(false);
        outputRD.setBackground(new java.awt.Color(204, 204, 204));
        outputRD.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 70, 20));

        outputRTotal.setEditable(false);
        outputRTotal.setBackground(new java.awt.Color(204, 204, 204));
        outputRTotal.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputRTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 70, 20));

        powerOutputTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        powerOutputTitle.setText("Power (Watts W)");
        outputWindow.add(powerOutputTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, 30));

        voltageOutputTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        voltageOutputTitle.setText("Voltage (Volts V)");
        outputWindow.add(voltageOutputTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        currentTitleA.setText("Current (A): ");
        outputWindow.add(currentTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, 20));

        currentTitleB.setText("Current (B):");
        outputWindow.add(currentTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        currentTitleC.setText("Current (C): ");
        outputWindow.add(currentTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        currentTitleD.setText("Current (D):");
        outputWindow.add(currentTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        currentTitleTotal.setText("Total current: ");
        outputWindow.add(currentTitleTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        outputIA.setEditable(false);
        outputIA.setBackground(new java.awt.Color(204, 204, 204));
        outputIA.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 70, 20));

        outputIB.setEditable(false);
        outputIB.setBackground(new java.awt.Color(204, 204, 204));
        outputIB.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 70, 20));

        outputIC.setEditable(false);
        outputIC.setBackground(new java.awt.Color(204, 204, 204));
        outputIC.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 70, 20));

        outputID.setEditable(false);
        outputID.setBackground(new java.awt.Color(204, 204, 204));
        outputID.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 70, 20));

        outputITotal.setEditable(false);
        outputITotal.setBackground(new java.awt.Color(204, 204, 204));
        outputITotal.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputITotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 70, 20));

        outputPA.setEditable(false);
        outputPA.setBackground(new java.awt.Color(204, 204, 204));
        outputPA.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 70, 20));

        outputPB.setEditable(false);
        outputPB.setBackground(new java.awt.Color(204, 204, 204));
        outputPB.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 70, 20));

        outputPC.setEditable(false);
        outputPC.setBackground(new java.awt.Color(204, 204, 204));
        outputPC.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 70, 20));

        outputPD.setEditable(false);
        outputPD.setBackground(new java.awt.Color(204, 204, 204));
        outputPD.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 70, 20));

        outputPTotal.setEditable(false);
        outputPTotal.setBackground(new java.awt.Color(204, 204, 204));
        outputPTotal.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        outputWindow.add(outputPTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 70, 20));

        powerTitleA.setText("Power (A): ");
        outputWindow.add(powerTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, 20));

        powerTitleB.setText("Power (B):");
        outputWindow.add(powerTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        powerTitleC.setText("Power (C): ");
        outputWindow.add(powerTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        powerTitleD.setText("Power (D):");
        outputWindow.add(powerTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        powerTitleTotal.setText("Total power: ");
        outputWindow.add(powerTitleTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        resistanceOutputTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        resistanceOutputTitle.setText("Resistance (Ohms)");
        outputWindow.add(resistanceOutputTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 30));

        currentOutputTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        currentOutputTitle.setText("Current (Amps A)");
        outputWindow.add(currentOutputTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 30));

        helpMenu.setText("Help");

        aboutThis.setText("About this program...");
        aboutThis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutThisActionPerformed(evt);
            }
        });
        helpMenu.add(aboutThis);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    OTHER STUFF
    */
    private void circuitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuitMenuActionPerformed
        
        circuitType = circuitMenu.getSelectedIndex();
        
        switch (circuitMenu.getSelectedIndex()) {
            case SERIES: 
                initSeriesInputFields();
                clearOutputFields();
                break;
            
            case PARALLEL: 
                initParallelDisplay();
                clearOutputFields();
                break;
            
            case PARALLEL_IN_SERIES: 
                initParallelInSeriesDisplay();
                clearOutputFields();
                break;
            
            case MULTI_LOOP: 
                initMultiLoopDisplay();
                clearOutputFields();
                break;
        }
    }//GEN-LAST:event_circuitMenuActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        
        switch (circuitType) {
            case SERIES: 
                try {
                    int batteries = Integer.parseInt(numberOfBatteriesInput.getText());
                    int voltage   = Integer.parseInt(voltagePerBatteryInput.getText());
                    int resistors = Integer.parseInt(noOfRInputASeries.getText());
                    int resistance= Integer.parseInt(rPerRInputASeries.getText());
                    
                    Series s = new Series(batteries, voltage, resistors, resistance);
                    
                    outputVoltA.setText(Double.toString(truncateNum(s.getTotalVoltage())));
                    outputVoltTotal.setText(Double.toString(truncateNum(s.getTotalVoltage())));
                    outputRA.setText(Double.toString(truncateNum(s.getResistanceAtA())));
                    outputRTotal.setText(Double.toString(truncateNum(s.getTotalResistance())));
                    outputIA.setText(Double.toString(truncateNum(s.getCurrentAtA())));
                    outputITotal.setText(Double.toString(truncateNum(s.getTotalCurrent())));
                    outputPA.setText(Double.toString(truncateNum(s.getPowerAtA())));
                    outputPTotal.setText(Double.toString(truncateNum(s.getTotalPower())));
                    
                    runningOKLabel.setVisible(true);
                    idleLabel.setVisible(false);
                    cb.add(s);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            
            case PARALLEL: 
                try {
                    int batteries  = Integer.parseInt(numberOfBatteriesInput.getText());
                    int voltage    = Integer.parseInt(voltagePerBatteryInput.getText());
                    
                    int resistorsA = Integer.parseInt(noOfRInputAParallel.getText());
                    int resistanceA= Integer.parseInt(rPerRInputAParallel.getText());
                    int resistorsB = Integer.parseInt(noOfRInputBParallel.getText());
                    int resistanceB= Integer.parseInt(rPerRInputBParallel.getText());
                    
                    Parallel p = new Parallel(batteries, voltage, resistorsA, resistanceA,
                                           resistorsB, resistanceB);
                    
                    outputVoltA.setText(Double.toString(truncateNum(p.getVoltageAtA())));
                    outputVoltB.setText(Double.toString(truncateNum(p.getVoltageAtB())));
                    outputVoltTotal.setText(Double.toString(truncateNum(p.getTotalVoltage())));
                    
                    outputRA.setText(Double.toString(truncateNum(p.getResistanceAtA())));
                    outputRB.setText(Double.toString(truncateNum(p.getResistanceAtB())));
                    outputRTotal.setText(Double.toString(truncateNum(p.getTotalResistance())));
                    
                    outputIA.setText(Double.toString(truncateNum(p.getCurrentAtA())));
                    outputIB.setText(Double.toString(truncateNum(p.getCurrentAtB())));
                    outputITotal.setText(Double.toString(truncateNum(p.getTotalCurrent())));
                    
                    outputPA.setText(Double.toString(truncateNum(p.getPowerAtA())));
                    outputPB.setText(Double.toString(truncateNum(p.getPowerAtB())));
                    outputPTotal.setText(Double.toString(truncateNum(p.getTotalPower())));
                    
                    runningOKLabel.setVisible(true);
                    idleLabel.setVisible(false);
                    cb.add(p);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            
            case PARALLEL_IN_SERIES: 
                try {
                    int batteries  = Integer.parseInt(numberOfBatteriesInput.getText());
                    int voltage    = Integer.parseInt(voltagePerBatteryInput.getText());
                    int resistorsA = Integer.parseInt(noOfRInputAParallelInSeries.getText());
                    int resistanceA= Integer.parseInt(rPerRInputAParallelInSeries.getText());
                    int resistorsC = Integer.parseInt(noOfRInputCParallelInSeries.getText());
                    int resistanceC= Integer.parseInt(rPerRInputCParallelInSeries.getText());
                    
                    ParallelInSeries ps = new ParallelInSeries(batteries, voltage, resistorsA,
                                                   resistanceA, resistorsC, resistanceC);
                    
                    outputVoltA.setText(Double.toString(truncateNum(ps.getVoltageAtA())));
                    outputVoltB.setText(Double.toString(truncateNum(ps.getVoltageAtB())));
                    outputVoltC.setText(Double.toString(truncateNum(ps.getVoltageAtC())));
                    outputVoltTotal.setText(Double.toString(truncateNum(ps.getTotalVoltage())));
                    
                    outputRA.setText(Double.toString(truncateNum(ps.getResistanceAtA())));
                    outputRC.setText(Double.toString(truncateNum(ps.getResistanceAtC())));
                    outputRTotal.setText(Double.toString(truncateNum(ps.getTotalResistance())));
                    
                    outputIA.setText(Double.toString(truncateNum(ps.getCurrentAtA())));
                    outputIB.setText(Double.toString(truncateNum(ps.getCurrentAtB())));
                    outputIC.setText(Double.toString(truncateNum(ps.getCurrentAtC())));
                    outputITotal.setText(Double.toString(truncateNum(ps.getTotalCurrent())));
                    
                    outputPA.setText(Double.toString(truncateNum(ps.getPowerAtA())));
                    outputPB.setText(Double.toString(truncateNum(ps.getPowerAtB())));
                    outputPC.setText(Double.toString(truncateNum(ps.getPowerAtC())));
                    outputPTotal.setText(Double.toString(truncateNum(ps.getTotalPower())));
                    
                    runningOKLabel.setVisible(true);
                    idleLabel.setVisible(false);
                    
                    cb.add(ps);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            
            case MULTI_LOOP: 
                try {
                    int batteries  = Integer.parseInt(numberOfBatteriesInput.getText());
                    int voltage    = Integer.parseInt(voltagePerBatteryInput.getText());
                    int resistorsA = Integer.parseInt(noOfRInputAMultiLoop.getText());
                    int resistanceA= Integer.parseInt(rPerRInputAMultiLoop.getText());
                    int resistorsB = Integer.parseInt(noOfRInputBMultiLoop.getText());
                    int resistanceB= Integer.parseInt(rPerRInputBMultiLoop.getText());
                    int resistorsC = Integer.parseInt(noOfRInputCMultiLoop.getText());
                    int resistanceC= Integer.parseInt(rPerRInputCMultiLoop.getText());
                    int resistorsD = Integer.parseInt(noOfRInputDMultiLoop.getText());
                    int resistanceD= Integer.parseInt(rPerRInputDMultiLoop.getText());
                    
                    MultiLoop ml = new MultiLoop(batteries, voltage, resistorsA, resistanceA, 
                                            resistorsB, resistanceB, resistorsC, resistanceC,
                                            resistorsD, resistanceD);
                    
                    outputVoltA.setText(Double.toString(truncateNum(ml.getVoltageAtA())));
                    outputVoltB.setText(Double.toString(truncateNum(ml.getVoltageAtB())));
                    outputVoltC.setText(Double.toString(truncateNum(ml.getVoltageAtC())));
                    outputVoltD.setText(Double.toString(truncateNum(ml.getVoltageAtD())));
                    outputVoltTotal.setText(Double.toString(truncateNum(ml.getTotalVoltage())));
                    
                    outputRA.setText(Double.toString(truncateNum(ml.getResistanceAtA())));
                    outputRB.setText(Double.toString(truncateNum(ml.getResistanceAtB())));
                    outputRC.setText(Double.toString(truncateNum(ml.getResistanceAtC())));
                    outputRD.setText(Double.toString(truncateNum(ml.getResistanceAtD())));
                    outputRTotal.setText(Double.toString(truncateNum(ml.getTotalResistance())));
                    
                    outputIA.setText(Double.toString(truncateNum(ml.getCurrentAtA())));
                    outputIB.setText(Double.toString(truncateNum(ml.getCurrentAtB())));
                    outputIC.setText(Double.toString(truncateNum(ml.getCurrentAtC())));
                    outputID.setText(Double.toString(truncateNum(ml.getCurrentAtD())));
                    outputITotal.setText(Double.toString(truncateNum(ml.getTotalCurrent())));
                    
                    outputPA.setText(Double.toString(truncateNum(ml.getPowerAtA())));
                    outputPB.setText(Double.toString(truncateNum(ml.getPowerAtB())));
                    outputPC.setText(Double.toString(truncateNum(ml.getPowerAtC())));
                    outputPD.setText(Double.toString(truncateNum(ml.getPowerAtD())));
                    outputPTotal.setText(Double.toString(truncateNum(ml.getTotalPower())));
                    
                    runningOKLabel.setVisible(true);
                    idleLabel.setVisible(false);
                    
                    cb.add(ml);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
        
    }//GEN-LAST:event_runButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        shutItDown(); 
        // persisting should happen IN the shutitdown method?
    }//GEN-LAST:event_formWindowClosing

    private void aboutThisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutThisActionPerformed
        String message = "Welcome to Circuit Simulator 2011! :^)\n\n" + 
                "As the title suggests, this program simulates a series of circuits, including\n" +
                "the classic series and parallel circuits, as well as two special circuits, \n" +
                "parallel in series and a multiloop circuit. \n" +
                "This program only deals with the basic properties of circuits, i.e. p.d./emf,\n" +
                "resistance, current, and power. You won't find capacitors or diodes here!\n\n" +
                "Just put in values of voltage and resistance into the fields, hit run, and\n" +
                "watch the magic happen.";
        JOptionPane.showMessageDialog(null, message, "Hello!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutThisActionPerformed

    
    // my methods
    private void clearImage() {
        seriesImage.setVisible(false);
        parallelImage.setVisible(false);
        parallelInSeriesImage.setVisible(false);
        multiLoopImage.setVisible(false);
        
        idleLabel.setVisible(true);
        runningOKLabel.setVisible(false);
    }
    
    private void initSeriesInputFields() {
        // display the right image
        seriesImage.setVisible(true);
        parallelImage.setVisible(false);
        parallelInSeriesImage.setVisible(false);
        multiLoopImage.setVisible(false);
        
        // display the right input jpanel
        seriesInputInfo.setVisible(true);
        parallelInputInfo.setVisible(false);
        parallelInSeriesInputInfo.setVisible(false);
        multiLoopInputInfo.setVisible(false);
        
        // initialize input text fields
        Circuit c = cb.getBucket()[UI.SERIES];
        if(c != null) {
            String state = c.getState();
            String[] stateArray = state.split(" ");
            numberOfBatteriesInput.setText(stateArray[0]);
            voltagePerBatteryInput.setText(stateArray[1]);
            rPerRInputASeries.setText(stateArray[2]);
            noOfRInputASeries.setText(stateArray[3]);
        }
        else {
            numberOfBatteriesInput.setText("");
            voltagePerBatteryInput.setText("");
            rPerRInputASeries.setText("");
            noOfRInputASeries.setText("");
        }  
    }
    
    private void initParallelDisplay() {
        // display the right image
        seriesImage.setVisible(false);
        parallelImage.setVisible(true);
        parallelInSeriesImage.setVisible(false);
        multiLoopImage.setVisible(false);
                
        //display the right jpanel
        seriesInputInfo.setVisible(false);
        parallelInputInfo.setVisible(true);
        parallelInSeriesInputInfo.setVisible(false);
        multiLoopInputInfo.setVisible(false);
        
        // clear input text fields
        Circuit c = cb.getBucket()[UI.SERIES];
        if(c != null) {
            String state = c.getState();
            String[] stateArray = state.split(" ");
            numberOfBatteriesInput.setText(stateArray[0]);
            voltagePerBatteryInput.setText(stateArray[1]);
            rPerRInputASeries.setText(stateArray[2]);
            noOfRInputASeries.setText(stateArray[3]);
            //rPerRInputBSeries.setText(stateArray[2]);
            //noOfRInputBSeries.setText(stateArray[3]);
        }
        else {
            numberOfBatteriesInput.setText("");
            voltagePerBatteryInput.setText("");
            rPerRInputAParallel.setText("");
            noOfRInputAParallel.setText("");
            rPerRInputBParallel.setText("");
            noOfRInputBParallel.setText("");
        }
    }
    
    private void initParallelInSeriesDisplay() {
        // display the right image
        seriesImage.setVisible(false);
        parallelImage.setVisible(false);
        parallelInSeriesImage.setVisible(true);
        multiLoopImage.setVisible(false);
            
        //display the right jpanel
        seriesInputInfo.setVisible(false);
        parallelInputInfo.setVisible(false);
        parallelInSeriesInputInfo.setVisible(true);
        multiLoopInputInfo.setVisible(false);
        
        //clear input text fields
        numberOfBatteriesInput.setText("");
        voltagePerBatteryInput.setText("");
        noOfRInputAParallelInSeries.setText("");
        rPerRInputAParallelInSeries.setText("");
        noOfRInputCParallelInSeries.setText("");
        rPerRInputCParallelInSeries.setText("");
    }
    
    private void initMultiLoopDisplay() {
        // display the right image
        seriesImage.setVisible(false);
        parallelImage.setVisible(false);
        parallelInSeriesImage.setVisible(false);
        multiLoopImage.setVisible(true);
        
        // display the right jpanel
        seriesInputInfo.setVisible(false);
        parallelInputInfo.setVisible(false);
        parallelInSeriesInputInfo.setVisible(false);
        multiLoopInputInfo.setVisible(true);
        
        //clear input text fields
        numberOfBatteriesInput.setText("");
        voltagePerBatteryInput.setText("");
        noOfRInputAMultiLoop.setText("");
        rPerRInputAMultiLoop.setText("");
        noOfRInputBMultiLoop.setText("");
        rPerRInputBMultiLoop.setText("");
        noOfRInputCMultiLoop.setText("");
        rPerRInputCMultiLoop.setText("");
        noOfRInputDMultiLoop.setText("");
        rPerRInputDMultiLoop.setText("");
    }
    
    private void shutItDown(){
        // Ask user if they really want to exit
        int choice = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to close? Your current inputted values will "
                        + "be saved for the next session.", "woah hey slow down cowboy",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        // Check user response
        if (choice == JOptionPane.OK_OPTION) {
            // maybe here is where the persisting happens?
            
            Persistor pers = new Persistor();

                try{
                    pers.initiate();
                    pers.write(cb);
                    pers.close();
                }
                
                catch(IOException e){
                    System.out.println("\n*** " + e.getMessage() + "\n"); //what is this even doing?
                }
            
            System.exit(0);
        }
    }
    
    private void clearOutputFields(){
        outputVoltA.setText("");
        outputVoltB.setText("");
        outputVoltC.setText("");
        outputVoltD.setText("");
        outputVoltTotal.setText("");

        outputRA.setText("");
        outputRB.setText("");
        outputRC.setText("");
        outputRD.setText("");
        outputRTotal.setText("");

        outputIA.setText("");
        outputIB.setText("");
        outputIC.setText("");
        outputID.setText("");
        outputITotal.setText("");

        outputPA.setText("");
        outputPB.setText("");
        outputPC.setText("");
        outputPD.setText("");
        outputPTotal.setText("");
    }
    
    private double truncateNum(double d){
        double newD = (Math.round(d * 100.0)) / 100.0;
        return newD;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CircuitSelectorPanel;
    private javax.swing.JMenuItem aboutThis;
    private javax.swing.JLabel battVoltTitleA;
    private javax.swing.JLabel battVoltTitleB;
    private javax.swing.JLabel battVoltTitleC;
    private javax.swing.JLabel battVoltTitleD;
    private javax.swing.JLabel battVoltTitleTotal;
    private javax.swing.JComboBox circuitMenu;
    private javax.swing.JLabel currentOutputTitle;
    private javax.swing.JLabel currentTitleA;
    private javax.swing.JLabel currentTitleB;
    private javax.swing.JLabel currentTitleC;
    private javax.swing.JLabel currentTitleD;
    private javax.swing.JLabel currentTitleTotal;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel idleLabel;
    private javax.swing.JPanel inputWindow;
    private javax.swing.JPanel mainWindow;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel multiLoopImage;
    private javax.swing.JPanel multiLoopInputInfo;
    private javax.swing.JTextField noOfRInputAMultiLoop;
    private javax.swing.JTextField noOfRInputAParallel;
    private javax.swing.JTextField noOfRInputAParallelInSeries;
    private javax.swing.JTextField noOfRInputASeries;
    private javax.swing.JTextField noOfRInputBMultiLoop;
    private javax.swing.JTextField noOfRInputBParallel;
    private javax.swing.JTextField noOfRInputCMultiLoop;
    private javax.swing.JTextField noOfRInputCParallelInSeries;
    private javax.swing.JTextField noOfRInputDMultiLoop;
    private javax.swing.JTextField numberOfBatteriesInput;
    private javax.swing.JLabel numberOfBatteriesLabel;
    private javax.swing.JLabel numberOfResistorsAtATitle;
    private javax.swing.JLabel numberOfResistorsTitleA;
    private javax.swing.JLabel numberOfResistorsTitleA1;
    private javax.swing.JLabel numberOfResistorsTitleA2;
    private javax.swing.JLabel numberOfResistorsTitleB;
    private javax.swing.JLabel numberOfResistorsTitleB1;
    private javax.swing.JLabel numberOfResistorsTitleC;
    private javax.swing.JLabel numberOfResistorsTitleC1;
    private javax.swing.JLabel numberOfResistorsTitleD;
    private javax.swing.JTextField outputIA;
    private javax.swing.JTextField outputIB;
    private javax.swing.JTextField outputIC;
    private javax.swing.JTextField outputID;
    private javax.swing.JTextField outputITotal;
    private javax.swing.JTextField outputPA;
    private javax.swing.JTextField outputPB;
    private javax.swing.JTextField outputPC;
    private javax.swing.JTextField outputPD;
    private javax.swing.JTextField outputPTotal;
    private javax.swing.JTextField outputRA;
    private javax.swing.JTextField outputRB;
    private javax.swing.JTextField outputRC;
    private javax.swing.JTextField outputRD;
    private javax.swing.JTextField outputRTotal;
    private javax.swing.JTextField outputVoltA;
    private javax.swing.JTextField outputVoltB;
    private javax.swing.JTextField outputVoltC;
    private javax.swing.JTextField outputVoltD;
    private javax.swing.JTextField outputVoltTotal;
    private javax.swing.JPanel outputWindow;
    private javax.swing.JLabel parallelImage;
    private javax.swing.JLabel parallelInSeriesImage;
    private javax.swing.JPanel parallelInSeriesInputInfo;
    private javax.swing.JPanel parallelInputInfo;
    private javax.swing.JLabel powerOutputTitle;
    private javax.swing.JLabel powerTitleA;
    private javax.swing.JLabel powerTitleB;
    private javax.swing.JLabel powerTitleC;
    private javax.swing.JLabel powerTitleD;
    private javax.swing.JLabel powerTitleTotal;
    private javax.swing.JTextField rPerRInputAMultiLoop;
    private javax.swing.JTextField rPerRInputAParallel;
    private javax.swing.JTextField rPerRInputAParallelInSeries;
    private javax.swing.JTextField rPerRInputASeries;
    private javax.swing.JTextField rPerRInputBMultiLoop;
    private javax.swing.JTextField rPerRInputBParallel;
    private javax.swing.JTextField rPerRInputCMultiLoop;
    private javax.swing.JTextField rPerRInputCParallelInSeries;
    private javax.swing.JTextField rPerRInputDMultiLoop;
    private javax.swing.JLabel resistanceOutputTitle;
    private javax.swing.JLabel resistancePerResistorATitle;
    private javax.swing.JLabel resistancePerResistorTitleA;
    private javax.swing.JLabel resistancePerResistorTitleA1;
    private javax.swing.JLabel resistancePerResistorTitleA3;
    private javax.swing.JLabel resistancePerResistorTitleB;
    private javax.swing.JLabel resistancePerResistorTitleB1;
    private javax.swing.JLabel resistancePerResistorTitleC;
    private javax.swing.JLabel resistancePerResistorTitleC1;
    private javax.swing.JLabel resistancePerResistorTitleD;
    private javax.swing.JLabel resistanceTitleA;
    private javax.swing.JLabel resistanceTitleB;
    private javax.swing.JLabel resistanceTitleC;
    private javax.swing.JLabel resistanceTitleD;
    private javax.swing.JLabel resistanceTitleTotal;
    private javax.swing.JButton runButton;
    private javax.swing.JLabel runningOKLabel;
    private javax.swing.JLabel seriesImage;
    private javax.swing.JPanel seriesInputInfo;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel voltageOutputTitle;
    private javax.swing.JTextField voltagePerBatteryInput;
    private javax.swing.JLabel voltagePerBatteryLabel;
    // End of variables declaration//GEN-END:variables
}
