/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package circuitsimulator;

/**
 *
 * @author tklw06
 */
public class CircuitSimulatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CircuitSimulator2
     */
    public CircuitSimulatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        mainWindow = new javax.swing.JPanel();
        circuitName = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        parallelInSeriesImage = new javax.swing.JLabel();
        multiLoopImage = new javax.swing.JLabel();
        parallelImage = new javax.swing.JLabel();
        seriesImage = new javax.swing.JLabel();
        inputWindow = new javax.swing.JPanel();
        multiLoopInputInfo = new javax.swing.JPanel();
        numberOfResistorsTitleA2 = new javax.swing.JLabel();
        resistancePerResistorTitleA3 = new javax.swing.JLabel();
        numberOfResistorsInputA2 = new javax.swing.JTextField();
        resistancePerResistorInputA2 = new javax.swing.JTextField();
        numberOfResistorsTitleB1 = new javax.swing.JLabel();
        resistancePerResistorTitleB1 = new javax.swing.JLabel();
        resistancePerResistorInputB1 = new javax.swing.JTextField();
        numberOfResistorsInputB1 = new javax.swing.JTextField();
        numberOfResistorsTitleC1 = new javax.swing.JLabel();
        resistancePerResistorTitleC1 = new javax.swing.JLabel();
        resistancePerResistorInputC1 = new javax.swing.JTextField();
        numberOfResistorsInputC1 = new javax.swing.JTextField();
        numberOfResistorsTitleD = new javax.swing.JLabel();
        resistancePerResistorTitleD = new javax.swing.JLabel();
        resistancePerResistorInputD = new javax.swing.JTextField();
        numberOfResistorsInputD = new javax.swing.JTextField();
        parallelInSeriesInputInfo = new javax.swing.JPanel();
        numberOfResistorsTitleA1 = new javax.swing.JLabel();
        resistancePerResistorTitleA1 = new javax.swing.JLabel();
        numberOfResistorsInputA1 = new javax.swing.JTextField();
        resistancePerResistorInputA1 = new javax.swing.JTextField();
        numberOfResistorsTitleC = new javax.swing.JLabel();
        resistancePerResistorTitleC = new javax.swing.JLabel();
        resistancePerResistorInputC = new javax.swing.JTextField();
        numberOfResistorsInputC = new javax.swing.JTextField();
        seriesInputInfo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberOfResistorsInput1 = new javax.swing.JTextField();
        resistancePerResistorInput1 = new javax.swing.JTextField();
        parallelInputInfo = new javax.swing.JPanel();
        numberOfResistorsTitleA = new javax.swing.JLabel();
        resistancePerResistorTitleA = new javax.swing.JLabel();
        numberOfResistorsInputA = new javax.swing.JTextField();
        resistancePerResistorInputA = new javax.swing.JTextField();
        numberOfResistorsTitleB = new javax.swing.JLabel();
        resistancePerResistorTitleB = new javax.swing.JLabel();
        resistancePerResistorInputB = new javax.swing.JTextField();
        numberOfResistorsInputB = new javax.swing.JTextField();
        numberOfBatteriesLabel = new javax.swing.JLabel();
        voltagePerBatteryLabel = new javax.swing.JLabel();
        numberOfBatteriesInput = new javax.swing.JTextField();
        voltagePerBatteryInput = new javax.swing.JTextField();
        CircuitSelectorPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        outputWindow = new javax.swing.JPanel();
        battVoltTitleA = new javax.swing.JLabel();
        battVoltTitleB = new javax.swing.JLabel();
        battVoltTitleTotal = new javax.swing.JLabel();
        battVoltTitleC = new javax.swing.JLabel();
        battVoltTitleD = new javax.swing.JLabel();
        outputVoltA = new javax.swing.JTextField();
        outputVoltB = new javax.swing.JTextField();
        outputVoltC = new javax.swing.JTextField();
        outputVoltD = new javax.swing.JTextField();
        outputVoltTotal = new javax.swing.JTextField();
        resistanceTitleA = new javax.swing.JLabel();
        resistanceTitleB = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circuitName.setText("Circuit: [.......]");
        mainWindow.add(circuitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, -1, -1));

        status.setText("Status: [......]");
        mainWindow.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 28, -1, -1));

        parallelInSeriesImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/parallelinseries.png"))); // NOI18N
        parallelInSeriesImage.setText("jLabel12");
        mainWindow.add(parallelInSeriesImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 290));

        multiLoopImage.setBackground(java.awt.Color.white);
        multiLoopImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/multiloop.png"))); // NOI18N
        mainWindow.add(multiLoopImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 412, 286));

        parallelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/parallel.png"))); // NOI18N
        mainWindow.add(parallelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 290));

        seriesImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circuitsimulator/series.png"))); // NOI18N
        mainWindow.add(seriesImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 290));

        inputWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Information"));
        inputWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        multiLoopInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfResistorsTitleA2.setText("Number of resistors (A):");
        multiLoopInputInfo.add(numberOfResistorsTitleA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        resistancePerResistorTitleA3.setText("Resistance per resistor (A): ");
        multiLoopInputInfo.add(resistancePerResistorTitleA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 180, -1));

        numberOfResistorsInputA2.setText("jTextField7");
        numberOfResistorsInputA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputA2ActionPerformed(evt);
            }
        });
        multiLoopInputInfo.add(numberOfResistorsInputA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 50, 20));

        resistancePerResistorInputA2.setText("jTextField7");
        multiLoopInputInfo.add(resistancePerResistorInputA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 20));

        numberOfResistorsTitleB1.setText("Number of resistors (B):");
        multiLoopInputInfo.add(numberOfResistorsTitleB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 172, -1));

        resistancePerResistorTitleB1.setText("Resistance per resistor (B): ");
        multiLoopInputInfo.add(resistancePerResistorTitleB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        resistancePerResistorInputB1.setText("jTextField7");
        multiLoopInputInfo.add(resistancePerResistorInputB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 50, 20));

        numberOfResistorsInputB1.setText("jTextField7");
        numberOfResistorsInputB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputB1ActionPerformed1(evt);
            }
        });
        multiLoopInputInfo.add(numberOfResistorsInputB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 20));

        numberOfResistorsTitleC1.setText("Number of resistors (C):");
        multiLoopInputInfo.add(numberOfResistorsTitleC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 172, -1));

        resistancePerResistorTitleC1.setText("Resistance per resistor (C): ");
        multiLoopInputInfo.add(resistancePerResistorTitleC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, -1));

        resistancePerResistorInputC1.setText("jTextField7");
        multiLoopInputInfo.add(resistancePerResistorInputC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, 20));

        numberOfResistorsInputC1.setText("jTextField7");
        numberOfResistorsInputC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputC1numberOfResistorsInputB1ActionPerformed(evt);
            }
        });
        multiLoopInputInfo.add(numberOfResistorsInputC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 50, 20));

        numberOfResistorsTitleD.setText("Number of resistors (D):");
        multiLoopInputInfo.add(numberOfResistorsTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 172, -1));

        resistancePerResistorTitleD.setText("Resistance per resistor (D): ");
        multiLoopInputInfo.add(resistancePerResistorTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, -1));

        resistancePerResistorInputD.setText("jTextField7");
        multiLoopInputInfo.add(resistancePerResistorInputD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 50, 20));

        numberOfResistorsInputD.setText("jTextField7");
        numberOfResistorsInputD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputDActionPerformed(evt);
            }
        });
        multiLoopInputInfo.add(numberOfResistorsInputD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 20));

        inputWindow.add(multiLoopInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 220));

        parallelInSeriesInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfResistorsTitleA1.setText("Number of resistors (A):");
        parallelInSeriesInputInfo.add(numberOfResistorsTitleA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        resistancePerResistorTitleA1.setText("Resistance per resistor (A): ");
        parallelInSeriesInputInfo.add(resistancePerResistorTitleA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 180, -1));

        numberOfResistorsInputA1.setText("jTextField7");
        numberOfResistorsInputA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputA1ActionPerformed(evt);
            }
        });
        parallelInSeriesInputInfo.add(numberOfResistorsInputA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 50, 20));

        resistancePerResistorInputA1.setText("jTextField7");
        parallelInSeriesInputInfo.add(resistancePerResistorInputA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 20));

        numberOfResistorsTitleC.setText("Number of resistors (C):");
        parallelInSeriesInputInfo.add(numberOfResistorsTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 172, -1));

        resistancePerResistorTitleC.setText("Resistance per resistor (C): ");
        parallelInSeriesInputInfo.add(resistancePerResistorTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        resistancePerResistorInputC.setText("jTextField7");
        parallelInSeriesInputInfo.add(resistancePerResistorInputC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 50, 20));

        numberOfResistorsInputC.setText("jTextField7");
        numberOfResistorsInputC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputCnumberOfResistorsInputB1ActionPerformed(evt);
            }
        });
        parallelInSeriesInputInfo.add(numberOfResistorsInputC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 20));

        inputWindow.add(parallelInSeriesInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 220));

        seriesInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Number of resistors: ");
        seriesInputInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        jLabel4.setText("Resistance per resistor: ");
        seriesInputInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 163, -1));

        numberOfResistorsInput1.setText("jTextField7");
        numberOfResistorsInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInput1ActionPerformed(evt);
            }
        });
        seriesInputInfo.add(numberOfResistorsInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 50, 20));

        resistancePerResistorInput1.setText("jTextField7");
        seriesInputInfo.add(resistancePerResistorInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 20));

        inputWindow.add(seriesInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 220));

        parallelInputInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberOfResistorsTitleA.setText("Number of resistors (A):");
        parallelInputInfo.add(numberOfResistorsTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 172, -1));

        resistancePerResistorTitleA.setText("Resistance per resistor (A): ");
        parallelInputInfo.add(resistancePerResistorTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 180, -1));

        numberOfResistorsInputA.setText("jTextField7");
        numberOfResistorsInputA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputAActionPerformed(evt);
            }
        });
        parallelInputInfo.add(numberOfResistorsInputA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 50, 20));

        resistancePerResistorInputA.setText("jTextField7");
        parallelInputInfo.add(resistancePerResistorInputA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 20));

        numberOfResistorsTitleB.setText("Number of resistors (B):");
        parallelInputInfo.add(numberOfResistorsTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 172, -1));

        resistancePerResistorTitleB.setText("Resistance per resistor (B): ");
        parallelInputInfo.add(resistancePerResistorTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        resistancePerResistorInputB.setText("jTextField7");
        parallelInputInfo.add(resistancePerResistorInputB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 50, 20));

        numberOfResistorsInputB.setText("jTextField7");
        numberOfResistorsInputB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfResistorsInputBActionPerformed(evt);
            }
        });
        parallelInputInfo.add(numberOfResistorsInputB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 20));

        inputWindow.add(parallelInputInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 220));

        numberOfBatteriesLabel.setText("Number of batteries:");
        inputWindow.add(numberOfBatteriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        voltagePerBatteryLabel.setText("Emf per battery: ");
        inputWindow.add(voltagePerBatteryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        numberOfBatteriesInput.setText("jTextField6");
        inputWindow.add(numberOfBatteriesInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 50, 20));

        voltagePerBatteryInput.setText("jTextField7");
        inputWindow.add(voltagePerBatteryInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 50, 20));

        mainWindow.add(inputWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 270, 290));

        CircuitSelectorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Circuit Selection"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout CircuitSelectorPanelLayout = new javax.swing.GroupLayout(CircuitSelectorPanel);
        CircuitSelectorPanel.setLayout(CircuitSelectorPanelLayout);
        CircuitSelectorPanelLayout.setHorizontalGroup(
            CircuitSelectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CircuitSelectorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        CircuitSelectorPanelLayout.setVerticalGroup(
            CircuitSelectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CircuitSelectorPanelLayout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainWindow.add(CircuitSelectorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 270, 50));

        outputWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Information"));
        outputWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        battVoltTitleA.setText("Voltage (A):");
        outputWindow.add(battVoltTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        battVoltTitleB.setText("Voltage (B):");
        outputWindow.add(battVoltTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        battVoltTitleTotal.setText("Total voltage: ");
        outputWindow.add(battVoltTitleTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        battVoltTitleC.setText("Voltage (C):");
        outputWindow.add(battVoltTitleC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        battVoltTitleD.setText("Voltage (D): ");
        outputWindow.add(battVoltTitleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        outputVoltA.setText("jTextField6");
        outputWindow.add(outputVoltA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        outputVoltB.setText("jTextField7");
        outputWindow.add(outputVoltB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        outputVoltC.setText("jTextField8");
        outputWindow.add(outputVoltC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        outputVoltD.setText("jTextField9");
        outputWindow.add(outputVoltD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        outputVoltTotal.setText("jTextField6");
        outputWindow.add(outputVoltTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        resistanceTitleA.setText("Resistance (A): ");
        outputWindow.add(resistanceTitleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 20));

        resistanceTitleB.setText("Resistance (B):");
        outputWindow.add(resistanceTitleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addComponent(outputWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outputWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfResistorsInputA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputA2ActionPerformed

    private void numberOfResistorsInputB1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputB1ActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputB1ActionPerformed1

    private void numberOfResistorsInputC1numberOfResistorsInputB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputC1numberOfResistorsInputB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputC1numberOfResistorsInputB1ActionPerformed

    private void numberOfResistorsInputDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputDActionPerformed

    private void numberOfResistorsInputA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputA1ActionPerformed

    private void numberOfResistorsInputCnumberOfResistorsInputB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputCnumberOfResistorsInputB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputCnumberOfResistorsInputB1ActionPerformed

    private void numberOfResistorsInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInput1ActionPerformed

    private void numberOfResistorsInputAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputAActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputAActionPerformed

    private void numberOfResistorsInputBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfResistorsInputBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfResistorsInputBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CircuitSimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircuitSimulatorGUI().setVisible(true);
            }
        });
    }

    /*
        //create array
        int[][] numbers = new int[10][12]; //10 rows. 4 will be default 
                                           //presets, hopefully the rest can be made?
        //initialize array: rows then columns
        for(int i = 0; i < numbers.length; i++){
            for (int n = 0; n < numbers[i].length; n++){
                numbers[i][n] = i*n;
            }
        } 
    */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CircuitSelectorPanel;
    private javax.swing.JLabel battVoltTitleA;
    private javax.swing.JLabel battVoltTitleB;
    private javax.swing.JLabel battVoltTitleC;
    private javax.swing.JLabel battVoltTitleD;
    private javax.swing.JLabel battVoltTitleTotal;
    private javax.swing.JLabel circuitName;
    private javax.swing.JPanel inputWindow;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainWindow;
    private javax.swing.JLabel multiLoopImage;
    private javax.swing.JPanel multiLoopInputInfo;
    private javax.swing.JTextField numberOfBatteriesInput;
    private javax.swing.JLabel numberOfBatteriesLabel;
    private javax.swing.JTextField numberOfResistorsInput1;
    private javax.swing.JTextField numberOfResistorsInputA;
    private javax.swing.JTextField numberOfResistorsInputA1;
    private javax.swing.JTextField numberOfResistorsInputA2;
    private javax.swing.JTextField numberOfResistorsInputB;
    private javax.swing.JTextField numberOfResistorsInputB1;
    private javax.swing.JTextField numberOfResistorsInputC;
    private javax.swing.JTextField numberOfResistorsInputC1;
    private javax.swing.JTextField numberOfResistorsInputD;
    private javax.swing.JLabel numberOfResistorsTitleA;
    private javax.swing.JLabel numberOfResistorsTitleA1;
    private javax.swing.JLabel numberOfResistorsTitleA2;
    private javax.swing.JLabel numberOfResistorsTitleB;
    private javax.swing.JLabel numberOfResistorsTitleB1;
    private javax.swing.JLabel numberOfResistorsTitleC;
    private javax.swing.JLabel numberOfResistorsTitleC1;
    private javax.swing.JLabel numberOfResistorsTitleD;
    private javax.swing.JTextField outputVoltA;
    private javax.swing.JTextField outputVoltB;
    private javax.swing.JTextField outputVoltC;
    private javax.swing.JTextField outputVoltD;
    private javax.swing.JTextField outputVoltTotal;
    private javax.swing.JPanel outputWindow;
    private javax.swing.JLabel parallelImage;
    private javax.swing.JLabel parallelInSeriesImage;
    private javax.swing.JPanel parallelInSeriesInputInfo;
    private javax.swing.JPanel parallelInputInfo;
    private javax.swing.JTextField resistancePerResistorInput1;
    private javax.swing.JTextField resistancePerResistorInputA;
    private javax.swing.JTextField resistancePerResistorInputA1;
    private javax.swing.JTextField resistancePerResistorInputA2;
    private javax.swing.JTextField resistancePerResistorInputB;
    private javax.swing.JTextField resistancePerResistorInputB1;
    private javax.swing.JTextField resistancePerResistorInputC;
    private javax.swing.JTextField resistancePerResistorInputC1;
    private javax.swing.JTextField resistancePerResistorInputD;
    private javax.swing.JLabel resistancePerResistorTitleA;
    private javax.swing.JLabel resistancePerResistorTitleA1;
    private javax.swing.JLabel resistancePerResistorTitleA3;
    private javax.swing.JLabel resistancePerResistorTitleB;
    private javax.swing.JLabel resistancePerResistorTitleB1;
    private javax.swing.JLabel resistancePerResistorTitleC;
    private javax.swing.JLabel resistancePerResistorTitleC1;
    private javax.swing.JLabel resistancePerResistorTitleD;
    private javax.swing.JLabel resistanceTitleA;
    private javax.swing.JLabel resistanceTitleB;
    private javax.swing.JLabel seriesImage;
    private javax.swing.JPanel seriesInputInfo;
    private javax.swing.JLabel status;
    private javax.swing.JTextField voltagePerBatteryInput;
    private javax.swing.JLabel voltagePerBatteryLabel;
    // End of variables declaration//GEN-END:variables
}
